"""
AI Text Generator Detector
===========================

Detects whether text was likely generated by AI (e.g., ChatGPT, GPT-4)
or written by a human. Purely relies on a trained ML classifier using TF-IDF.
"""

import os
import joblib

try:
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score, classification_report
    HAS_SKLEARN = True
except ImportError:
    HAS_SKLEARN = False

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
AI_DETECTOR_MODEL_PATH = os.path.join(SCRIPT_DIR, "models", "ai_detector_model.pkl")
AI_DETECTOR_VECTORIZER_PATH = os.path.join(SCRIPT_DIR, "models", "ai_detector_vectorizer.pkl")
CSV_PATH = os.path.join(SCRIPT_DIR, "data", "AI_Human.csv")

# Lazy-loaded trained model
_ai_model = None
_ai_vectorizer = None


def _load_ai_model():
    """Lazy-load the trained AI detector model if available."""
    global _ai_model, _ai_vectorizer
    if _ai_model is None and os.path.exists(AI_DETECTOR_MODEL_PATH):
        _ai_model = joblib.load(AI_DETECTOR_MODEL_PATH)
        _ai_vectorizer = joblib.load(AI_DETECTOR_VECTORIZER_PATH)
    return _ai_model, _ai_vectorizer


def detect_ai_text(text: str) -> dict:
    """
    Detect AI text using the trained ML model.
    """
    model, vectorizer = _load_ai_model()
    
    # If model is not found, attempt to train it instantly if dataset exists
    if model is None:
        if os.path.exists(CSV_PATH):
            print("Model not found. Initializing auto-training with the dataset...")
            train_ai_detector(CSV_PATH)
            model, vectorizer = _load_ai_model()
        else:
            return {
                "error": "Model not trained and dataset not found.",
                "verdict": "unknown",
                "method": "pure_ml_classifier"
            }
            
    text_vec = vectorizer.transform([text])
    probability = model.predict_proba(text_vec)[0]
    
    # 1 corresponds to AI, 0 corresponds to Human mapping
    ai_prob = float(probability[1])
    human_prob = float(probability[0])
    
    if ai_prob >= 0.65:
        verdict = "likely_ai"
    elif ai_prob >= 0.40:
        verdict = "uncertain"
    else:
        verdict = "likely_human"
        
    return {
        "ai_probability": round(ai_prob * 100, 1),
        "human_probability": round(human_prob * 100, 1),
        "verdict": verdict,
        "confidence": round(max(ai_prob, human_prob) * 100, 1),
        "method": "pure_ml_classifier"
    }


def train_ai_detector(csv_path: str = CSV_PATH, sample_size: int = 40000):
    """
    Train an AI text detector purely from a labeled CSV dataset.
    Extracts text and applies a TF-IDF vectorization to learn patterns
    distinguishing Human and AI texts.
    
    Args:
        csv_path: Path to the CSV file
        sample_size: Number of records to sample (default 40k to prevent OOM on 1GB file)
    """
    if not HAS_SKLEARN:
        raise RuntimeError("scikit-learn and pandas are required for training. Please: pip install scikit-learn pandas")
        
    import pandas as pd
    
    print(f"Loading dataset from: {csv_path}")
    # Read the large CSV file
    df = pd.read_csv(csv_path)
    
    # Detect the correct columns based on the CSV structure
    text_col = "text" if "text" in df.columns else "content_text"
    label_col = "generated" if "generated" in df.columns else "author_type"
    
    print(f"  Total samples found: {len(df)}")
    
    # Sample down the dataset to prevent memory issues and train faster
    if len(df) > sample_size:
        print(f"  Dataset is extremely large. Sampling randomly to {sample_size} records to avoid memory crashes...")
        df = df.sample(n=sample_size, random_state=42)
        
    print(f"  Training sample size: {len(df)}")
    print(f"  Author distribution: {dict(df[label_col].value_counts())}")
    
    X = df[text_col].fillna("")
    
    # Parse the labels (0.0 for Human, 1.0 for AI)
    y = pd.to_numeric(df[label_col], errors='coerce').fillna(0).astype(int)
        
    # Standard splitting strategy
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    
    print("Executing TF-IDF vectorization on text fields...")
    vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1, 2), stop_words="english")
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)
    
    print("Training ML Classifier (Random Forest)...")
    model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    model.fit(X_train_vec, y_train)
    
    y_pred = model.predict(X_test_vec)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"\nModel Accuracy: {accuracy * 100:.2f}%")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["Human", "AI-Generated"]))
    
    joblib.dump(model, AI_DETECTOR_MODEL_PATH)
    joblib.dump(vectorizer, AI_DETECTOR_VECTORIZER_PATH)
    print(f"-> Model saved to: {AI_DETECTOR_MODEL_PATH}")
    print(f"-> Vectorizer saved to: {AI_DETECTOR_VECTORIZER_PATH}")
    
    # Ensure cache is invalidated for the next immediate use
    global _ai_model, _ai_vectorizer
    _ai_model = None
    _ai_vectorizer = None
    
    return {"accuracy": accuracy}


if __name__ == "__main__":
    train_ai_detector()
